version: '3.8'

services:
  app:
    image: booking-futsal_app:latest
    container_name: futsal-neo-s-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    networks:
      - futsal-network
    environment:
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-futsal_booking}
      - DB_USERNAME=${DB_USERNAME:-futsal_user}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    cpus: 1.0
    mem_limit: 512m
    mem_reservation: 256m

  db:
    image: docker.io/library/mysql:8.0
    container_name: futsal-neo-s-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-futsal_booking}
      MYSQL_USER: ${DB_USERNAME:-futsal_user}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - futsal-network
    command: --default-authentication-plugin=mysql_native_password --max_connections=500
    cpus: 0.5
    mem_limit: 512m
    mem_reservation: 256m

  nginx:
    image: docker.io/library/nginx:alpine
    container_name: futsal-neo-s-nginx
    restart: unless-stopped
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - futsal-network
      - traefik-network
    depends_on:
      - app
    cpus: 0.5
    mem_limit: 256m
    mem_reservation: 128m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.futsal-nginx.rule=Host(`kelompok1-de.humahub.my.id`)"
      - "traefik.http.routers.futsal-nginx.entrypoints=websecure"
      - "traefik.http.services.futsal-nginx.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-network"
      - traefik.http.routers.futsal-nginx.tls=true
      - traefik.http.routers.futsal-nginx.tls.certresolver=cf


networks:
  futsal-network:
    driver: bridge
  traefik-network:
    external: true

volumes:
  db_data:
    driver: local
